name: CL Tryjobs

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Get code
      - name: Checkout repository
        uses: actions/checkout@v3

    # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

    # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deps.txt

    # Run all Python files
      - name: Run all Python files
        run: |
          for f in $(find . -name "*.py"); do
            echo "Running $f"
            python "$f" || exit 1
          done
